site_name: JymKit
site_url: https://ponseko.github.io/jymkit/
repo_url: https://github.com/ponseko/jymkit
theme:
  name: material
  features:
    - navigation.sections  # Sections are included in the navigation on the left.
    - navigation.instant
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: white
      accent: red
      toggle:
          icon: material/weather-night
          name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
          icon: material/weather-sunny
          name: Switch to light mode

extra_css:
  - _static/styles.css

strict: true # Do not allow warnings

markdown_extensions:
  - pymdownx.superfences  # Seems to enable syntax highlighting when used with the Material theme.
  - pymdownx.details  # Allowing hidden expandable regions denoted by ???
  - pymdownx.snippets:  # Include one Markdown file into another
      base_path: docs
  - admonition
  - toc:
      permalink: "¤"  # Adds a clickable permalink to each section heading
      toc_depth: 4

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 4
            inherited_members: true
            members_order: source
            group_by_category: false
            show_bases: false
            show_if_no_docstring: true
            show_overloads: false
            show_root_heading: true
            show_signature_annotations: true
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
  - search

nav:
  - 'index.md'
  - Environments:
    - 'api/Environment.md'
    # - 'api/Multi-Agent.md'
    - 'api/Spaces.md'
    - 'api/Wrappers.md'
