name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: patrick-kidger/action_update_python_project@v7
        with:
            python-version: "3.11"
            test-script: |
                cp -r ${{ github.workspace }}/tests ./tests
                cp ${{ github.workspace }}/pyproject.toml ./pyproject.toml
                export JYMKIT_SKIP_CLI_TEST=1
                uv sync --dev --no-install-project --inexact
                uv run --no-sync pytest
            pypi-token: ${{ secrets.pypi_token }}
            github-user: ponseko
            github-token: ${{ github.token }}  # automatically created token