name: Run Tests

on:
  pull_request:

jobs:
  run-test:
    strategy:
      matrix:
        python-version: [ "3.10", "3.11" ]
        os: [ ubuntu-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Ruff linting and formatting
        uses: astral-sh/ruff-action@v3

      - name: Run tests
        run: |
          python -m pip install --upgrade pip '.[algs]'
          python -m pip install -r tests/requirements.txt
          python -m pytest

      - name: Check that docs can be built
        run: |
          python -m pip install mkdocs-material
          mkdocs build